services:
  postgres:
    image: postgres:16
    container_name: expert-label-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: expert_label
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d expert_label"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

