from __future__ import annotations

import json
from dataclasses import dataclass
from urllib import error, request


class LLMServiceError(RuntimeError):
    pass


@dataclass(slots=True)
class LLMClientConfig:
    enabled: bool = False
    provider: str = "mock"
    base_url: str = ""
    api_key: str = ""
    model: str = "mock-model"
    timeout: float = 30.0
    temperature: float = 0.2
    slot_name: str = "default"


@dataclass(slots=True)
class LLMGenerateResult:
    content: str
    provider: str
    model: str


class LLMService:
    def __init__(self, config: LLMClientConfig | None = None) -> None:
        self.config = config or LLMClientConfig()

    def generate_response(self, prompt: str) -> LLMGenerateResult:
        normalized_prompt = prompt.strip()
        if not normalized_prompt:
            raise LLMServiceError("Prompt 不能为空")

        provider = self.config.provider.strip().lower() or "mock"
        if provider == "mock":
            return LLMGenerateResult(
                content=self._build_mock_response(normalized_prompt),
                provider="mock",
                model=self.config.model,
            )

        if not self.config.enabled:
            raise LLMServiceError(f"{self.config.slot_name} 模型配置未启用")

        if provider not in {"openai", "openai_compatible"}:
            raise LLMServiceError(f"暂不支持的模型提供方: {self.config.provider}")

        return self._call_openai_compatible(normalized_prompt)

    def _build_mock_response(self, prompt: str) -> str:
        first_line = next((line.strip() for line in prompt.splitlines() if line.strip()), prompt)
        preview = first_line[:120]
        return (
            "This is a mock model response generated by the backend.\n\n"
            f"Prompt focus: {preview}\n\n"
            "Suggested answer:\n"
            "1. Address the user request directly.\n"
            "2. Keep the response clear and structured.\n"
            "3. Cover the main constraints and avoid unsupported claims."
        )

    def _call_openai_compatible(self, prompt: str) -> LLMGenerateResult:
        base_url = self.config.base_url.strip().rstrip("/")
        if not base_url:
            raise LLMServiceError("模型服务 base_url 未配置")
        if not self.config.api_key.strip():
            raise LLMServiceError("模型服务 api_key 未配置")

        payload = {
            "model": self.config.model,
            "temperature": self.config.temperature,
            "messages": [
                {
                    "role": "system",
                    "content": "You are generating a single model response for an expert review task.",
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        }

        req = request.Request(
            url=f"{base_url}/chat/completions",
            method="POST",
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.config.api_key.strip()}",
            },
            data=json.dumps(payload).encode("utf-8"),
        )

        try:
            with request.urlopen(req, timeout=self.config.timeout) as response:
                raw = response.read().decode("utf-8")
        except error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            raise LLMServiceError(f"模型服务调用失败: {detail or exc.reason}") from exc
        except error.URLError as exc:
            raise LLMServiceError(f"模型服务不可用: {exc.reason}") from exc
        except TimeoutError as exc:
            raise LLMServiceError("模型服务响应超时") from exc

        try:
            parsed = json.loads(raw)
            content = parsed["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError, json.JSONDecodeError) as exc:
            raise LLMServiceError("模型服务返回格式不正确") from exc

        if not isinstance(content, str) or not content.strip():
            raise LLMServiceError("模型未返回有效内容")

        return LLMGenerateResult(
            content=content.strip(),
            provider=self.config.provider,
            model=self.config.model,
        )
