from __future__ import annotations

TASK_STATUS_ANNOTATION_PENDING = "annotation_pending"
TASK_STATUS_ANNOTATION_IN_PROGRESS = "annotation_in_progress"
TASK_STATUS_PENDING_REVIEW_DISPATCH = "pending_review_dispatch"
TASK_STATUS_REVIEW_PENDING = "review_pending"
TASK_STATUS_REVIEW_IN_PROGRESS = "review_in_progress"
TASK_STATUS_REVIEW_SUBMITTED = "review_submitted"
TASK_STATUS_APPROVED = "approved"

REVIEW_STATUS_PENDING = "pending"
REVIEW_STATUS_IN_PROGRESS = "in_progress"
REVIEW_STATUS_WAITING_RESUBMISSION = "waiting_resubmission"
REVIEW_STATUS_SUBMITTED = "submitted"

REVIEW_OWNED_STATUSES = {
    REVIEW_STATUS_IN_PROGRESS,
    REVIEW_STATUS_WAITING_RESUBMISSION,
}

ANNOTATION_AVAILABLE_STATUSES = {
    TASK_STATUS_ANNOTATION_PENDING,
}

ANNOTATION_ACTIVE_STATUSES = {
    TASK_STATUS_ANNOTATION_IN_PROGRESS,
}

ANNOTATION_OWNED_STATUSES = {
    TASK_STATUS_ANNOTATION_IN_PROGRESS,
    TASK_STATUS_PENDING_REVIEW_DISPATCH,
    TASK_STATUS_REVIEW_PENDING,
    TASK_STATUS_REVIEW_IN_PROGRESS,
    TASK_STATUS_REVIEW_SUBMITTED,
}

TASK_COMPLETED_STATUSES = {
    TASK_STATUS_APPROVED,
}
